version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE}'
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    volumes:
      - /var/lib/mongo:/data/db
    networks:
      - mongo
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${ME_CONFIG_MONGODB_ADMINUSERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${ME_CONFIG_MONGODB_ADMINPASSWORD}'
      ME_CONFIG_MONGODB_URL: '${ME_CONFIG_MONGODB_URL}'
    depends_on:
      - mongo
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
